language: python
python:
  - "3.6"
env:
  - DJANGO='Django==1.11.*'
  - DJANGO='Django==2.0.*'
  - DJANGO='Django==2.1.*'
  - DJANGO='Django==2.2.*'
install:
  - pip install $DJANGO
script:
  - make test
