language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO='Django==1.8.*'
  - DJANGO='Django==1.9.*'
  - DJANGO='Django==1.10.*'
  - DJANGO='Django==1.11.*'
  - DJANGO='Django==2.0.*'
  - DJANGO='Django==2.1.*'
matrix:
  exclude:
    # Django >= 2 does not support Python 2.7
    - python: "2.7"
      env: DJANGO='Django==2.0.*'
    - python: "2.7"
      env: DJANGO='Django==2.1.*'
    - python: "3.5"
      env: DJANGO='Django==2.0.*'
    - python: "3.5"
      env: DJANGO='Django==2.1.*'
install:
  - pip install $DJANGO
script:
  - make test
